name: cert
services:

  nginx:
#    depends_on:
#      - wordpress
    image: nginx:1.29-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - ./single:/var/www/single:ro
      - ./support:/var/www/support:ro
      - acme-challenge:/var/www/acme-challenge:ro
      - certbot-etc:/etc/letsencrypt:ro
    networks:
      - hubs
    healthcheck:
      test: ['CMD', 'curl', 'http://127.0.0.1/healthz']
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  certbot:
    container_name: certbot
    depends_on:
      nginx: { condition: service_healthy }
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - acme-challenge:/var/www/acme-challenge
    command: certonly --webroot --webroot-path=/var/www/acme-challenge --expand --email hominidsoftware@gmail.com --agree-tos --force-renewal --non-interactive -d ${HUB_DOMAIN:?error} -d support.${HUB_DOMAIN:?error}


volumes:
  certbot-etc:
  acme-challenge:

networks:
  hubs:
